# Generated by Django 5.1 on 2024-09-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='dataCriacao',
            field=models.DateTimeField(auto_now_add=True, default='2024-09-04', verbose_name='Data de Criação'),
            preserve_default=False,
        ),
    ]
